config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :recipes, :cuisines, :recipe_types

  get '/search', to: 'recipes#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, uniqueness: { message: 'Essa cozinha ja existe'}
  validates :name, presence: { message: 'Você deve informar o nome da cozinha'}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  validates :title, :recipe_type_id, :cuisine_id, :difficulty, :cook_time,
  :ingredients, :method, presence: {
    message: 'Você deve informar todos os dados da receita'}
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, uniqueness: { message: 'Esse tipo de receita ja existe'}
  validates :name, presence: { message: 'Você deve informar o nome do tipo de receita'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
    @recipe = Recipe.where(:cuisine => params[:id])
  end
  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)

    if @cuisine.save
      redirect_to @cuisine
    else
      render 'new'
    end
  end

  def edit
    @cuisine = Cuisine.find(params[:id])
  end

  def update
    @cuisine = Cuisine.find(params[:id])
    if @cuisine.update(cuisine_params)
      redirect_to @cuisine
    else
      render 'edit'
    end
  end

  private
  def cuisine_params
    params.require(:cuisine).permit(:name)

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_types = RecipeType.find(params[:id])
    @recipe = Recipe.where(:recipe_type => params[:id])
  end
  def new
    @recipe_type = RecipeType.new
  end

  def create
    recipe_type_name = params.require(:recipe_type).permit(:name)
    @recipe_type = RecipeType.new(recipe_type_name)

    if @recipe_type.save
      redirect_to @recipe_type
    else
      render :new
    end
  end

  def edit
    @recipe_type = RecipeType.find(params[:id])
  end

  def update
    recipe_type_name = params.require(:recipe_type).permit(:name)
    @recipe_type = RecipeType.find(params[:id])
    if @recipe_type.update(recipe_type_name)
      redirect_to @recipe_type
    else
      render 'edit'
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Receita excluida com sucesso."
    redirect_to root_path
  end

  def search
    @busca = Recipe.find_by title: params[:Busca]
    if @busca.nil?
      flash[:notice] = "Receita não encontrada."
      redirect_to root_path
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id, :difficulty,
      :cook_time, :ingredients, :method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cuisines/_errors.html.erb
<% @cuisine.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

app/views/cuisines/_form.html.erb
<%= form_for @cuisine do |f| %>
  <p>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit "Enviar" %>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Editar Cozinha</h1>
<%= render "errors" %>
<%= render "form" %>
<%= link_to "Voltar", cuisine_path(@cuisine) %>

app/views/cuisines/new.html.erb
<h1>Registrar Cozinha</h1>
<%= render "errors" %>
<%= render "form" %>
<%= link_to "Voltar", root_path %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>
<%= link_to "Editar", edit_cuisine_path(@cuisine) %>
<% @recipe.each do |r| %>
  <h1><%= r.title %></h1>
  <ul>
    <li><%= r.recipe_type.name %></li>
    <li><%= r.cuisine.name %></li>
    <li><%= r.difficulty %></li>
    <li><%= r.cook_time %> minutos</li>
  </ul>
<% end %>

<% if @recipe.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>

<%= link_to "Voltar", root_path %>

app/views/home/index.html.erb
<h1><b>CookBook</b></h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= link_to "Enviar uma receita", new_recipe_path %>
<br>
<%= link_to "Criar tipo de receita", new_recipe_type_path %>
<br>
<%= link_to "Criar cozinha", new_cuisine_path %>
<br>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:Busca, "Busca:") %>
  <%= text_field_tag(:Busca) %>
  <%= submit_tag("Buscar") %>
<% end %>
<hr>

<div class="cuisine">
  <ul>
    <h3>Cozinha</h3>
    <% @cuisines.each do |c| %>
      <li><%= link_to c.name, cuisine_path(c.id)%></li>
    <% end %>
  </ul>
</div>

<div class="recipe_type">
  <ul>
    <h3>Receitas por tipo</h3>
    <% @recipe_types.each do |rt| %>
      <li><%= link_to rt.name, recipe_type_path(rt.id) %></li>
    <% end %>
  </ul>
</div>

<hr>

<h1>Ultimas receitas</h1>
<% @recipes.each do |r| %>
  <ul>
    <li><h1><%= link_to r.title, recipe_path(r.id) %></h1></li>
    <li><%= r.recipe_type.name %></li>
    <li><%= r.cuisine.name %></li>
    <li><%= r.difficulty %></li>
    <li><%= r.cook_time %> minutos</li>
  </ul>
  </tr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Praganacookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipe_types/_errors.html.erb
<% @recipe_type.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

app/views/recipe_types/_form.html.erb
<%= form_for @recipe_type do |f| %>
  <p>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit "Enviar" %>
<% end %> 

app/views/recipe_types/edit.html.erb
<h1>Editar tipo de receita</h1>

<%= render "errors" %>
<%= render "form" %>
<%= link_to "Voltar", root_path %>

app/views/recipe_types/new.html.erb
<h1>Registrar tipo de receita</h1>
<%= render "errors" %>
<%= render "form" %>
<%= link_to "Voltar", root_path %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_types.name %></h1>

<% @recipe.each do |r| %>
  <h1><%= r.title %></h1>
  <ul>
    <li><%= r.recipe_type.name %></li>
    <li><%= r.cuisine.name %></li>
    <li><%= r.difficulty %></li>
    <li><%= r.cook_time %> minutos</li>
  </ul>
<% end %>

<% if @recipe.empty? %>
  <p>Nenhuma receita encontrada para este tipo de receitas</p>
<% end %>
<%= link_to "Editar", edit_recipe_type_path(@recipe_types) %>
<%= link_to "Voltar", root_path %>

app/views/recipes/_errors.html.erb
<% @recipe.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<p>
  <%= f.label :title, "Título" %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :recipe_type_id, "Tipo da Receita" %>
  <%= f.collection_select :recipe_type_id, RecipeType.all, :id, :name %>
</p>
<p>
  <%= f.label :cuisine_id, "Cozinha" %>
  <%= f.collection_select :cuisine_id, Cuisine.all, :id, :name %>

</p>
<p>
  <%= f.label :difficulty, "Dificuldade" %>
  <%= f.text_field :difficulty %>
</p>
<p>
  <%= f.label :cook_time, "Tempo de Preparo" %>
  <%= f.text_field :cook_time %>
</p>
<p>
  <%= f.label :ingredients, "Ingredientes" %>
  <%= f.text_area :ingredients %>
</p>
<p>
  <%= f.label :method, "Como Preparar" %>
  <%= f.text_area :method %>
</p>
<%= f.submit "Enviar" %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editar receita</h1>

<%= render "errors" %>
<%= render "form" %>
<%= link_to "Voltar", root_path %>

app/views/recipes/new.html.erb
<h1>Registrando sua receita</h1>
<%= render "errors" %>
<%= render "form" %>
<%= link_to "Voltar", root_path %>

app/views/recipes/search.html.erb
<h1>Resultado da busca por: <%= @busca.title %></h1>

<h1><%= link_to @busca.title, recipe_path(@busca) %></h1>
<ul>
  <li><%= @busca.recipe_type.name %></li>
  <li><%= @busca.cuisine.name %></li>
  <li><%= @busca.difficulty %></li>
  <li><%= @busca.cook_time %> minutos</li>
</ul>

app/views/recipes/show.html.erb
<h1> <%= @recipe.title %> </h1>
<h3>Detalhes</h3>
<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.method %></p>

<%= link_to "Editar", edit_recipe_path(@recipe) %>
<%= link_to "Excluir", recipe_path(@recipe), method: :delete %>
<%= link_to "Voltar", root_path %>